# Generated by Django 5.1 on 2024-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticateapp', '0009_alter_appointmentmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='ap_id',
            field=models.CharField(blank=True, editable=False, max_length=11),
        ),
    ]
