# Generated by Django 5.1 on 2024-10-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticateapp', '0010_appointmentmodel_ap_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='ap_id',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='pat_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
